issues:
  exclude-rules:
    # Exclude issues bypassing staticcheck.conf
    - linters:
        - staticcheck
      text: "SA1019:"

  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - staticcheck

linters-settings:
  nolintlint:
    allow-unused: true # Because of the disabled rules with Go 1.18
    allow-leading-space: false
    require-explanation: true
    require-specific: true
    allow-no-explanation:
      - unparam
      - gomnd
  staticcheck:
    checks: ["all", "-SA1019"]
run:
  timeout: 75m
  go: 1.18
  skip-dirs:
    - .ci/providerlint/vendor
